apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chat-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chat-service
    spec:
      containers:
        - name: chat-service
          image: xiaopewpew/mesh-mono-chat-service:20250610.1749533258
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080