apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.16-debian-syslog-2
          # TODO: is root necessary?
          securityContext: # Run as root (for Minikube)
            allowPrivilegeEscalation: true
            runAsUser: 0
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: minikube-container-log-dir
              mountPath: /var/log/containers
              readOnly: true
            - name: minikube-pod-log-dir
              mountPath: /var/log/pods
              readOnly: true
            - name: minikube-lib-container-log-dir
              mountPath: /var/lib/docker/containers
              readOnly: true
      # it may be desirable to set a high priority class to ensure that a DaemonSet Pod
      # preempts running Pods
      # priorityClassName: important
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: minikube-container-log-dir
          hostPath:
            path: /var/log/containers
        - name: minikube-pod-log-dir
          hostPath:
            path: /var/log/pods
        - name: minikube-lib-container-log-dir
          hostPath:
            path: /var/lib/docker/containers