name: Docker Image For Blockchain Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SERVICE_NAME: blockchain-service

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    permissions:
      id-token: write  # for actions/attest-build-provenance
      attestations: write  # for actions/attest-build-provenance

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'zulu'
        cache: maven
        cache-dependency-path: '${{ env.SERVICE_NAME }}/pom.xml'

    - name: Build with Maven
      run: mvn clean package --file ${{ env.SERVICE_NAME }}/pom.xml

    - name: Extract metadata for Docker image labelling
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ vars.DOCKERHUB_USERNAME }}/mesh-mono-${{ env.SERVICE_NAME }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: push-docker-image
      uses: docker/build-push-action@v6
      with:
        context: ./${{ env.SERVICE_NAME }}
        file: ./${{ env.SERVICE_NAME }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
#
#    - name: Generate artifact attestation
#      uses: actions/attest-build-provenance@v2
#      with:
#        subject-name: index.docker.io/${{ vars.DOCKERHUB_USERNAME }}/mesh-mono-${{ env.SERVICE_NAME }}
#        subject-digest: ${{ steps.push-docker-image.outputs.digest }}
#        push-to-registry: true
