name: Docker Image For Blockchain Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'zulu'
        cache: maven
        cache-dependency-path: 'blockchain-service/pom.xml'

    - name: Build with Maven
      run: mvn clean package --file blockchain-service/pom.xml

    - name: Build the Docker image
      run: |
        docker build blockchain-service \
          --file blockchain-service/Dockerfile \
          --tag blockchain-service:$(date +%Y%m%d.%s)
