name: Docker Image For Blockchain Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'zulu'
        cache: maven
        cache-dependency-path: 'blockchain-service/pom.xml'

    - name: Build with Maven
      run: mvn clean package --file blockchain-service/pom.xml

    - name: Extract metadata for Docker image labelling
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: test  # TODO: figure out what this is...

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: push-docker-image
      uses: docker/build-push-action@v6
      with:
        context: ./blockchain-service
        file: ./blockchain-service/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: test  # TODO: figure out what this is...
        subject-digest: ${{ steps.push-docker-image.outputs.digest }}
        push-to-registry: true
